package backend;
// Generated Sep 30, 2015 10:47:13 PM by Hibernate Tools 4.3.1



/**
 * FeedbackResponses generated by hbm2java
 */
public class FeedbackResponses  implements java.io.Serializable {


     private Integer srNo;
     private String name;
     private String email;
     private String college;
     private String trade;
     private String year;
     private String event;
     private int presenterRating;
     private int contentRating;
     private int eventRating;
     private int overallRating;
     private String eventSynchronised;
     private String attendUpcoming;
     private String joinGdgjss;
     private String suggestions;

    public FeedbackResponses() {
    }

    public FeedbackResponses(String name, String email, String college, String trade, String year, String event, int presenterRating, int contentRating, int eventRating, int overallRating, String eventSynchronised, String attendUpcoming, String joinGdgjss, String suggestions) {
       this.name = name;
       this.email = email;
       this.college = college;
       this.trade = trade;
       this.year = year;
       this.event = event;
       this.presenterRating = presenterRating;
       this.contentRating = contentRating;
       this.eventRating = eventRating;
       this.overallRating = overallRating;
       this.eventSynchronised = eventSynchronised;
       this.attendUpcoming = attendUpcoming;
       this.joinGdgjss = joinGdgjss;
       this.suggestions = suggestions;
    }
   
    public Integer getSrNo() {
        return this.srNo;
    }
    
    public void setSrNo(Integer srNo) {
        this.srNo = srNo;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCollege() {
        return this.college;
    }
    
    public void setCollege(String college) {
        this.college = college;
    }
    public String getTrade() {
        return this.trade;
    }
    
    public void setTrade(String trade) {
        this.trade = trade;
    }
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }
    public String getEvent() {
        return this.event;
    }
    
    public void setEvent(String event) {
        this.event = event;
    }
    public int getPresenterRating() {
        return this.presenterRating;
    }
    
    public void setPresenterRating(int presenterRating) {
        this.presenterRating = presenterRating;
    }
    public int getContentRating() {
        return this.contentRating;
    }
    
    public void setContentRating(int contentRating) {
        this.contentRating = contentRating;
    }
    public int getEventRating() {
        return this.eventRating;
    }
    
    public void setEventRating(int eventRating) {
        this.eventRating = eventRating;
    }
    public int getOverallRating() {
        return this.overallRating;
    }
    
    public void setOverallRating(int overallRating) {
        this.overallRating = overallRating;
    }
    public String getEventSynchronised() {
        return this.eventSynchronised;
    }
    
    public void setEventSynchronised(String eventSynchronised) {
        this.eventSynchronised = eventSynchronised;
    }
    public String getAttendUpcoming() {
        return this.attendUpcoming;
    }
    
    public void setAttendUpcoming(String attendUpcoming) {
        this.attendUpcoming = attendUpcoming;
    }
    public String getJoinGdgjss() {
        return this.joinGdgjss;
    }
    
    public void setJoinGdgjss(String joinGdgjss) {
        this.joinGdgjss = joinGdgjss;
    }
    public String getSuggestions() {
        return this.suggestions;
    }
    
    public void setSuggestions(String suggestions) {
        this.suggestions = suggestions;
    }




}


