package backend;
// Generated Sep 30, 2015 10:47:13 PM by Hibernate Tools 4.3.1



/**
 * Administrators generated by hbm2java
 */
public class Administrators  implements java.io.Serializable {


     private Integer serialNo;
     private String adminName;
     private String adminEmail;

    public Administrators() {
    }

    public Administrators(String adminName, String adminEmail) {
       this.adminName = adminName;
       this.adminEmail = adminEmail;
    }
   
    public Integer getSerialNo() {
        return this.serialNo;
    }
    
    public void setSerialNo(Integer serialNo) {
        this.serialNo = serialNo;
    }
    public String getAdminName() {
        return this.adminName;
    }
    
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }
    public String getAdminEmail() {
        return this.adminEmail;
    }
    
    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail;
    }




}


