package backend;
// Generated Sep 30, 2015 10:47:13 PM by Hibernate Tools 4.3.1



/**
 * Check generated by hbm2java
 */
public class Check  implements java.io.Serializable {


     private Integer srno;
     private String fbEmail;
     private String eventname;

    public Check() {
    }

    public Check(String fbEmail, String eventname) {
       this.fbEmail = fbEmail;
       this.eventname = eventname;
    }
   
    public Integer getSrno() {
        return this.srno;
    }
    
    public void setSrno(Integer srno) {
        this.srno = srno;
    }
    public String getFbEmail() {
        return this.fbEmail;
    }
    
    public void setFbEmail(String fbEmail) {
        this.fbEmail = fbEmail;
    }
    public String getEventname() {
        return this.eventname;
    }
    
    public void setEventname(String eventname) {
        this.eventname = eventname;
    }




}


