package backend;
// Generated 27 Jan, 2016 9:02:33 PM by Hibernate Tools 4.3.1



/**
 * Responses generated by hbm2java
 */
public class Responses  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private String institute;
     private String trade;
     private String year;
     private int eval1;
     private int eval2;
     private int eval3;
     private int eval4;
     private String ques1;
     private String ques2;
     private String ques3;
     private String suggestion;
     private String event;

    public Responses() {
    }

    public Responses(String name, String email, String institute, String trade, String year, int eval1, int eval2, int eval3, int eval4, String ques1, String ques2, String ques3, String suggestion, String event) {
       this.name = name;
       this.email = email;
       this.institute = institute;
       this.trade = trade;
       this.year = year;
       this.eval1 = eval1;
       this.eval2 = eval2;
       this.eval3 = eval3;
       this.eval4 = eval4;
       this.ques1 = ques1;
       this.ques2 = ques2;
       this.ques3 = ques3;
       this.suggestion = suggestion;
       this.event = event;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getInstitute() {
        return this.institute;
    }
    
    public void setInstitute(String institute) {
        this.institute = institute;
    }
    public String getTrade() {
        return this.trade;
    }
    
    public void setTrade(String trade) {
        this.trade = trade;
    }
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }
    public int getEval1() {
        return this.eval1;
    }
    
    public void setEval1(int eval1) {
        this.eval1 = eval1;
    }
    public int getEval2() {
        return this.eval2;
    }
    
    public void setEval2(int eval2) {
        this.eval2 = eval2;
    }
    public int getEval3() {
        return this.eval3;
    }
    
    public void setEval3(int eval3) {
        this.eval3 = eval3;
    }
    public int getEval4() {
        return this.eval4;
    }
    
    public void setEval4(int eval4) {
        this.eval4 = eval4;
    }
    public String getQues1() {
        return this.ques1;
    }
    
    public void setQues1(String ques1) {
        this.ques1 = ques1;
    }
    public String getQues2() {
        return this.ques2;
    }
    
    public void setQues2(String ques2) {
        this.ques2 = ques2;
    }
    public String getQues3() {
        return this.ques3;
    }
    
    public void setQues3(String ques3) {
        this.ques3 = ques3;
    }
    public String getSuggestion() {
        return this.suggestion;
    }
    
    public void setSuggestion(String suggestion) {
        this.suggestion = suggestion;
    }
    public String getEvent() {
        return this.event;
    }
    
    public void setEvent(String event) {
        this.event = event;
    }




}


